FROM node:16-alpine as node

WORKDIR /usr/app
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm install @angular/cli -g
RUN ng build --configuration production --output-path=/dist

FROM nginx:1.21-alpine

COPY --from=node /dist /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
